# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DE.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08\x44\x45.proto\x12\x0b\x44\x45Messaging"\xbd\x02\n\x08\x44\x45Packet\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.DEMessaging.DEPacket.Type\x12\x19\n\x11\x63\x61mera_identifier\x18\x02 \x01(\r\x12+\n\x07\x63ommand\x18\x03 \x03(\x0b\x32\x1a.DEMessaging.SingleCommand\x12\x33\n\x0b\x61\x63knowledge\x18\x04 \x03(\x0b\x32\x1e.DEMessaging.SingleAcknowledge\x12,\n\x0b\x64\x61ta_header\x18\x05 \x01(\x0b\x32\x17.DEMessaging.DataHeader\x12\x13\n\x0b\x63\x61mera_name\x18\x06 \x01(\t"G\n\x04Type\x12\n\n\x06P_NULL\x10\x00\x12\r\n\tP_COMMAND\x10\x01\x12\x11\n\rP_ACKNOWLEDGE\x10\x02\x12\x11\n\rP_DATA_HEADER\x10\x03"g\n\rSingleCommand\x12\x12\n\ncommand_id\x18\x01 \x01(\r\x12\x14\n\x0c\x63ommand_name\x18\x02 \x01(\t\x12,\n\tparameter\x18\x03 \x03(\x0b\x32\x19.DEMessaging.AnyParameter"\xf0\x01\n\x0c\x41nyParameter\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.DEMessaging.AnyParameter.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05p_int\x18\x03 \x01(\x11\x12\x0e\n\x06p_bool\x18\x04 \x01(\x08\x12\x10\n\x08p_string\x18\x05 \x01(\t\x12\x0f\n\x07p_float\x18\x06 \x01(\x02\x12\x0f\n\x07p_bytes\x18\x07 \x01(\x0c"Q\n\x04Type\x12\n\n\x06P_NULL\x10\x00\x12\t\n\x05P_INT\x10\x01\x12\n\n\x06P_BOOL\x10\x02\x12\x0c\n\x08P_STRING\x10\x03\x12\x0b\n\x07P_FLOAT\x10\x04\x12\x0b\n\x07P_BYTES\x10\x05"]\n\x0b\x41\x63knowledge\x12\x19\n\x11\x63\x61mera_identifier\x18\x01 \x01(\r\x12\x33\n\x0b\x61\x63knowledge\x18\x02 \x03(\x0b\x32\x1e.DEMessaging.SingleAcknowledge"\x91\x01\n\x11SingleAcknowledge\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x12\n\ncommand_id\x18\x02 \x01(\r\x12\x14\n\x0c\x63ommand_name\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12,\n\tparameter\x18\x05 \x03(\x0b\x32\x19.DEMessaging.AnyParameter"2\n\nDataHeader\x12\x10\n\x08\x62ytesize\x18\x01 \x01(\x04\x12\x12\n\nidentifier\x18\x02 \x01(\tb\x06proto3'
)


_DEPACKET = DESCRIPTOR.message_types_by_name["DEPacket"]
_SINGLECOMMAND = DESCRIPTOR.message_types_by_name["SingleCommand"]
_ANYPARAMETER = DESCRIPTOR.message_types_by_name["AnyParameter"]
_ACKNOWLEDGE = DESCRIPTOR.message_types_by_name["Acknowledge"]
_SINGLEACKNOWLEDGE = DESCRIPTOR.message_types_by_name["SingleAcknowledge"]
_DATAHEADER = DESCRIPTOR.message_types_by_name["DataHeader"]
_DEPACKET_TYPE = _DEPACKET.enum_types_by_name["Type"]
_ANYPARAMETER_TYPE = _ANYPARAMETER.enum_types_by_name["Type"]
DEPacket = _reflection.GeneratedProtocolMessageType(
    "DEPacket",
    (_message.Message,),
    {
        "DESCRIPTOR": _DEPACKET,
        "__module__": "DE_pb2",
        # @@protoc_insertion_point(class_scope:DEMessaging.DEPacket)
    },
)
_sym_db.RegisterMessage(DEPacket)

SingleCommand = _reflection.GeneratedProtocolMessageType(
    "SingleCommand",
    (_message.Message,),
    {
        "DESCRIPTOR": _SINGLECOMMAND,
        "__module__": "DE_pb2",
        # @@protoc_insertion_point(class_scope:DEMessaging.SingleCommand)
    },
)
_sym_db.RegisterMessage(SingleCommand)

AnyParameter = _reflection.GeneratedProtocolMessageType(
    "AnyParameter",
    (_message.Message,),
    {
        "DESCRIPTOR": _ANYPARAMETER,
        "__module__": "DE_pb2",
        # @@protoc_insertion_point(class_scope:DEMessaging.AnyParameter)
    },
)
_sym_db.RegisterMessage(AnyParameter)

Acknowledge = _reflection.GeneratedProtocolMessageType(
    "Acknowledge",
    (_message.Message,),
    {
        "DESCRIPTOR": _ACKNOWLEDGE,
        "__module__": "DE_pb2",
        # @@protoc_insertion_point(class_scope:DEMessaging.Acknowledge)
    },
)
_sym_db.RegisterMessage(Acknowledge)

SingleAcknowledge = _reflection.GeneratedProtocolMessageType(
    "SingleAcknowledge",
    (_message.Message,),
    {
        "DESCRIPTOR": _SINGLEACKNOWLEDGE,
        "__module__": "DE_pb2",
        # @@protoc_insertion_point(class_scope:DEMessaging.SingleAcknowledge)
    },
)
_sym_db.RegisterMessage(SingleAcknowledge)

DataHeader = _reflection.GeneratedProtocolMessageType(
    "DataHeader",
    (_message.Message,),
    {
        "DESCRIPTOR": _DATAHEADER,
        "__module__": "DE_pb2",
        # @@protoc_insertion_point(class_scope:DEMessaging.DataHeader)
    },
)
_sym_db.RegisterMessage(DataHeader)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _DEPACKET._serialized_start = 26
    _DEPACKET._serialized_end = 343
    _DEPACKET_TYPE._serialized_start = 272
    _DEPACKET_TYPE._serialized_end = 343
    _SINGLECOMMAND._serialized_start = 345
    _SINGLECOMMAND._serialized_end = 448
    _ANYPARAMETER._serialized_start = 451
    _ANYPARAMETER._serialized_end = 691
    _ANYPARAMETER_TYPE._serialized_start = 610
    _ANYPARAMETER_TYPE._serialized_end = 691
    _ACKNOWLEDGE._serialized_start = 693
    _ACKNOWLEDGE._serialized_end = 786
    _SINGLEACKNOWLEDGE._serialized_start = 789
    _SINGLEACKNOWLEDGE._serialized_end = 934
    _DATAHEADER._serialized_start = 936
    _DATAHEADER._serialized_end = 986
# @@protoc_insertion_point(module_scope)
