PROP_ADUS_PER_ELECTRON = "ADUs Per Electron"
PROP_COINCIDENCE_LOSS_PARAMETER = "Coincidence Loss Calibration Parameter"
PROP_AUTOSAVE_COUNTED_MOVIE_PIXEL_FORMAT = "Autosave Counted Movie Pixel Format"
PROP_AUTOSAVE_CRUDE_FRAMES = "Autosave Crude Frames"
PROP_AUTOSAVE_CRUDE_FRAMES_FILE_PATH = "Autosave Crude Frames File Path"
PROP_AUTOSAVE_CRUDE_FRAMES_WRITTEN = "Autosave Crude Frames Written"
PROP_AUTOSAVE_DEBUG_FRAMES = "Autosave Debug Frames"
PROP_AUTOSAVE_DIRECTORY = "Autosave Directory"
PROP_AUTOSAVE_EXTERNAL_IMAGE_1 = "Autosave External Image 1"
PROP_AUTOSAVE_EXTERNAL_IMAGE_1_FILE_PATH = "Autosave External Image 1 File Path"
PROP_AUTOSAVE_EXTERNAL_IMAGE_1_FRAMES_WRITTEN = (
    "Autosave External Image 1 Frames Written"
)
PROP_AUTOSAVE_EXTERNAL_IMAGE_2 = "Autosave External Image 2"
PROP_AUTOSAVE_EXTERNAL_IMAGE_2_FILE_PATH = "Autosave External Image 2 File Path"
PROP_AUTOSAVE_EXTERNAL_IMAGE_2_FRAMES_WRITTEN = (
    "Autosave External Image 2 Frames Written"
)
PROP_AUTOSAVE_EXTERNAL_IMAGE_3 = "Autosave External Image 3"
PROP_AUTOSAVE_EXTERNAL_IMAGE_3_FILE_PATH = "Autosave External Image 3 File Path"
PROP_AUTOSAVE_EXTERNAL_IMAGE_3_FRAMES_WRITTEN = (
    "Autosave External Image 3 Frames Written"
)
PROP_AUTOSAVE_EXTERNAL_IMAGE_4 = "Autosave External Image 4"
PROP_AUTOSAVE_EXTERNAL_IMAGE_4_FILE_PATH = "Autosave External Image 4 File Path"
PROP_AUTOSAVE_EXTERNAL_IMAGE_4_FRAMES_WRITTEN = (
    "Autosave External Image 4 Frames Written"
)
PROP_AUTOSAVE_FILE_FORMAT = "Autosave File Format"
PROP_AUTOSAVE_FILENAME_SUFFIX = "Autosave Filename Suffix"
PROP_AUTOSAVE_FINAL_FRAMES_WRITTEN = "Autosave Final Frames Written"
PROP_AUTOSAVE_FINAL_FRAMES_MOTION_CORRECTED_WRITTEN = (
    "Autosave Final Motion Corrected Frames Written"
)
PROP_AUTOSAVE_FINAL_IMAGE = "Autosave Final Image"
PROP_AUTOSAVE_FINAL_IMAGE_SUM_COUNT = "Autosave Final Image Sum Count"
PROP_AUTOSAVE_FINISHED = "Autosave Finished"
PROP_AUTOSAVE_FINAL_MOTION_CORRECTED_IMAGE_FILE_PATH = (
    "Autosave Final Motion Corrected Image File Path"
)
PROP_AUTOSAVE_FINAL_IMAGE_FILE_PATH = "Autosave Final Image File Path"
PROP_AUTOSAVE_COUNTER = "Autosave Counter"
PROP_AUTOSAVE_MOVIE = "Autosave Movie"
PROP_AUTOSAVE_MOVIE_FRAMES_FILE_PATH = "Autosave Movie Frames File Path"
PROP_AUTOSAVE_MOVIE_FRAMES_WRITTEN = "Autosave Movie Frames Written"
PROP_AUTOSAVE_MOVIE_FILE_FORMAT = "Autosave Movie File Format"
PROP_AUTOSAVE_MOVIE_IGNORE_SOFTWARE_BINNING = "Autosave Movie Ignore Software Binning"
PROP_AUTOSAVE_MOVIE_SUM_COUNT = "Autosave Movie Sum Count"
PROP_AUTOSAVE_4D_FILE_FORMAT = "Autosave 4D File Format"
PROP_AUTOSAVE_VIRTUALEXT_FILE_FORMAT = "Autosave VirtualExt File Format"
PROP_AUTOSAVE_INTEGRATED_MOVIE_PIXEL_FORMAT = "Autosave Integrated Movie Pixel Format"
PROP_AUTOSAVE_LZW_ROWS_PER_STRIP = "Autosave LZW Rows Per Strip"
PROP_AUTOSAVE_SCAN_SUBSAMPLING_MASK = "Autosave Scan Subsampling Mask"
PROP_AUTOSAVE_STATUS = "Autosave Status"
PROP_AUTOSAVE_VIRTUAL_IMAGE_0 = "Autosave Virtual Image 0"
PROP_AUTOSAVE_VIRTUAL_IMAGE_1 = "Autosave Virtual Image 1"
PROP_AUTOSAVE_VIRTUAL_IMAGE_2 = "Autosave Virtual Image 2"
PROP_AUTOSAVE_VIRTUAL_IMAGE_3 = "Autosave Virtual Image 3"
PROP_AUTOSAVE_VIRTUAL_IMAGE_4 = "Autosave Virtual Image 4"
PROP_AUTOSAVE_VIRTUAL_IMAGE_0_FRAMES_WRITTEN = "Autosave Virtual Image 0 Frames Written"
PROP_AUTOSAVE_VIRTUAL_IMAGE_1_FRAMES_WRITTEN = "Autosave Virtual Image 1 Frames Written"
PROP_AUTOSAVE_VIRTUAL_IMAGE_2_FRAMES_WRITTEN = "Autosave Virtual Image 2 Frames Written"
PROP_AUTOSAVE_VIRTUAL_IMAGE_3_FRAMES_WRITTEN = "Autosave Virtual Image 3 Frames Written"
PROP_AUTOSAVE_VIRTUAL_IMAGE_4_FRAMES_WRITTEN = "Autosave Virtual Image 4 Frames Written"
PROP_AUTOSAVE_VIRTUAL_IMAGE_0_FILE_PATH = "Autosave Virtual Image 0 File Path"
PROP_AUTOSAVE_VIRTUAL_IMAGE_1_FILE_PATH = "Autosave Virtual Image 1 File Path"
PROP_AUTOSAVE_VIRTUAL_IMAGE_2_FILE_PATH = "Autosave Virtual Image 2 File Path"
PROP_AUTOSAVE_VIRTUAL_IMAGE_3_FILE_PATH = "Autosave Virtual Image 3 File Path"
PROP_AUTOSAVE_VIRTUAL_IMAGE_4_FILE_PATH = "Autosave Virtual Image 4 File Path"
PROP_BINNING_METHOD = "Binning Method"
PROP_BINNING_X = "Binning X"
PROP_BINNING_Y = "Binning Y"
PROP_CAMERA_AUTO_RETRACT_DELAY = "Camera Auto Retract Delay"
PROP_CAMERA_FAILSAFE_OVERRIDE = "Camera Failsafe Override"
PROP_CAMERA_FAILSAFE_STATUS = "Camera Failsafe Status"
PROP_CAMERA_MODEL = "Camera Model"
PROP_CAMERA_NAME = "Camera Name"
PROP_CAMERA_POSITION = "Camera Position"
PROP_CAMERA_POSITION_CONTROL = "Camera Position Control"
PROP_CAMERA_POSITION_OVERRIDE = "Camera Position Override"
PROP_CAMERA_POSITION_STATUS = "Camera Position Status"
PROP_CAMERA_SN = "Camera SN"
PROP_CHECK_TEM_CHANNEL = "Check TEM-Channel"
PROP_COMPUTER_CPU_INFO = "Computer CPU Info"
PROP_COMPUTER_GPU_INFO = "Computer GPU Info"
PROP_COMPUTER_MEMORY_INFO = "Computer Memory Info"
PROP_COMPUTER_NAME = "Computer Name"
PROP_CROP_OFFSET_X = "Crop Offset X"
PROP_CROP_OFFSET_Y = "Crop Offset Y"
PROP_CROP_SIZE_X = "Crop Size X"
PROP_CROP_SIZE_Y = "Crop Size Y"
PROP_DATASET_NAME = "Dataset Name"
PROP_DISK_SPACE_GB = "Disk Space (GB)"
PROP_DUMP_REGISTERS = "Dump Registers"
PROP_ELECTRON_COUNTING = "Electron Counting"
PROP_EVENT_COUNTING_APPLY_POST_COUNTING_GAIN = (
    "Event Counting - Apply Post-Counting Gain"
)
PROP_EVENT_COUNTING_APPLY_PRE_COUNTING_GAIN = "Event Counting - Apply Pre-Counting Gain"
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM = "Event Counting - Intensity Histogram"
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM_BINS = (
    "Event Counting - Intensity Histogram Bins"
)
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM_MAXIMUM = (
    "Event Counting - Intensity Histogram Maximum"
)
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM_MINIMUM = (
    "Event Counting - Intensity Histogram Minimum"
)
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM_ROI_OFFSET_X = (
    "Event Counting - Intensity Histogram ROI Offset X"
)
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM_ROI_OFFSET_Y = (
    "Event Counting - Intensity Histogram ROI Offset Y"
)
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM_ROI_SIZE_X = (
    "Event Counting - Intensity Histogram ROI Size X"
)
PROP_EVENT_COUNTING_INTENSITY_HISTOGRAM_ROI_SIZE_Y = (
    "Event Counting - Intensity Histogram ROI Size Y"
)
PROP_EVENT_COUNTING_TOTAL_EVENT_INTENSITY_MIN = (
    "Event Counting - Total Event Intensity Min"
)
PROP_EVENT_COUNTING_TOTAL_EVENT_INTENSITY_MAX = (
    "Event Counting - Total Event Intensity Max"
)
PROP_EVENT_COUNTING_METHOD = "Event Counting - Method"
PROP_EVENT_COUNTING_SPARSENESS = "Event Counting - Sparseness"
PROP_EVENT_COUNTING_SUPER_RESOLUTION = "Event Counting - Super Resolution"
PROP_EXPOSURE_MODE = "Exposure Mode"
PROP_EXPOSURE_RATE = "Exposure Rate (e-/pix/s)"
PROP_EXPOSURE_TIME_SECONDS = "Exposure Time (seconds)"
PROP_EXPOSURE_TIME_MAX_SECONDS = "Exposure Time Max (seconds)"
PROP_EXTERNAL_IMAGE_PIXEL_FORMAT = "External Image Pixel Format"
PROP_FARADAY_PLATE_CALIBRATION_MULTIPLIER = "Faraday Plate - Calibration Multiplier"
PROP_FARADAY_PLATE_LIFETIME_DOSE = "Faraday Plate - Lifetime Dose(e-/pix)"
PROP_FARADAY_PLATE_PEAK_INTENSITY_E_PIX_FRAME = (
    "Faraday Plate - Peak Intensity (e-/pix/frame)"
)
PROP_FARADAY_PLATE_PEAK_INTENSITY_E_PIX_S = "Faraday Plate - Peak Intensity (e-/pix/s)"
PROP_FARADAY_PLATE_PEAK_INTENSITY_PA_CM2 = "Faraday Plate - Peak Intensity (pA/cm^2)"
PROP_FARADAY_PLATE_TOTAL_DOSE = "Faraday Plate - Total Dose (e-/pix)"
PROP_FARADAY_PLATE_ZERO_POINT = "Faraday Plate - Zero Point"
PROP_FEATURE_AKRA = "Feature - AKRA"
PROP_FEATURE_ACTUATOR = "Feature - Actuator"
PROP_FEATURE_CENTERED = "Feature - Centered"
PROP_FEATURE_COUNTING = "Feature - Counting"
PROP_FEATURE_GLOBAL_SHUTTER = "Feature - Global Shutter"
PROP_FEATURE_HDR = "Feature - HDR"
PROP_FEATURE_HW_ROI_X = "Feature - HW ROI X"
PROP_FEATURE_HW_ROI_Y = "Feature - HW ROI Y"
PROP_FEATURE_OKRA = "Feature - OKRA"
PROP_FEATURE_OFF_CHIP_CDS = "Feature - Off-chip CDS"
PROP_FEATURE_SENSOR_GAIN = "Feature - Sensor Gain"
PROP_FEATURE_HARDWARE_COUNTING = "Feature - Hardware Counting"
PROP_FEATURE_HARDWARE_BINNING = "Feature - Hardware Binning"
PROP_FILE_PATH_BAD_PIXELS = "File Path - Bad Pixels"
PROP_FILE_PATH_CONFIGURATION = "File Path - Configuration"
PROP_FILE_PATH_LOG = "File Path - Log"
PROP_FILE_PATH_PRESETS = "File Path - Presets"
PROP_FIRMWARE_VERSION = "Firmware Version"
PROP_FRAME_COUNT = "Frame Count"
PROP_FRAME_EXPOSURE_TIME_NANOSECONDS = "Frame Exposure Time (nanoseconds)"
PROP_FRAME_TIME_NANOSECONDS = "Frame Time (nanoseconds)"
PROP_FRAMES_PER_SECOND = "Frames Per Second"
PROP_FRAMES_PER_SECOND_MAX = "Frames Per Second (Max)"
PROP_GPU_SELECTION = "GPU Selection"
PROP_GRAB_BUFFER_ALIGNMENT = "Grab Buffer Alignment"
PROP_GRAB_BUFFER_LENGTH_MILLISECONDS = "Grab Buffer Length (milliseconds)"
PROP_GRAB_BUFFER_SIZE = "Grab Buffer Size"
PROP_GRABBER_TYPE = "Grabber Type"
PROP_GRABBER_DROPPED_FRAMES = "Grabber Dropped Frames"
PROP_GRABBING_BIT_PACKING = "Grabbing - Bit Packing"
PROP_GRABBING_FRAMES_PER_BUFFER = "Grabbing - Frames Per Buffer"
PROP_GRABBING_TARGET_BUFFER_SIZE_MB = "Grabbing - Target Buffer Size (MB)"
PROP_HARDWARE_BINNING_X = "Hardware Binning X"
PROP_HARDWARE_BINNING_Y = "Hardware Binning Y"
PROP_HARDWARE_FRAME_SIZE_X = "Hardware Frame Size X"
PROP_HARDWARE_FRAME_SIZE_Y = "Hardware Frame Size Y"
PROP_HARDWARE_ROI_OFFSET_X = "Hardware ROI Offset X"
PROP_HARDWARE_ROI_OFFSET_Y = "Hardware ROI Offset Y"
PROP_HARDWARE_ROI_SIZE_X = "Hardware ROI Size X"
PROP_HARDWARE_ROI_SIZE_Y = "Hardware ROI Size Y"
PROP_HUMIDITY = "Humidity (%RH)"
PROP_IMAGE_PROCESSING_APPLY_GAIN_ON_FINAL = "Image Processing - Apply Gain on Final"
PROP_IMAGE_PROCESSING_APPLY_GAIN_ON_MOVIE = "Image Processing - Apply Gain on Movie"
PROP_IMAGE_PROCESSING_BAD_PIXEL_CORRECTION = "Image Processing - Bad Pixel Correction"
PROP_IMAGE_PROCESSING_BAD_PIXEL_AVERAGING = "Image Processing - Bad Pixel Averaging"
PROP_IMAGE_PROCESSING_EDGE_PIXEL_FILL = "Image Processing - Edge Pixel Fill"
PROP_IMAGE_PROCESSING_FLATFIELD_CORRECTION = "Image Processing - Flatfield Correction"
PROP_IMAGE_PROCESSING_FLIP_HORIZONTALLY = "Image Processing - Flip Horizontally"
PROP_IMAGE_PROCESSING_FLIP_VERTICALLY = "Image Processing - Flip Vertically"
PROP_IMAGE_PROCESSING_FOURIER_FILTER = "Image Processing - Fourier Filter"
PROP_IMAGE_PROCESSING_MODE = "Image Processing - Mode"
PROP_IMAGE_PROCESSING_OUTPUT_BUFFER_SIZE = "Image Processing - Output Buffer Size"
PROP_IMAGE_PROCESSING_ROTATION = "Image Processing - Rotation"
PROP_IMAGE_PROCESSING_SCALING_FACTOR = "Image Processing - Scaling Factor"
PROP_IMAGE_PROCESSING_PROGRESS_PERCENTAGE = "Image Processing - Progress Percentage"
PROP_IMAGE_SIZE_X_PIXELS = "Image Size X (pixels)"
PROP_IMAGE_SIZE_Y_PIXELS = "Image Size Y (pixels)"
PROP_INSTRUMENT_CLIENT_ADDRESS = "Instrument Client Address"
PROP_INSTRUMENT_METADATA = "Instrument Metadata"
PROP_INSTRUMENT_PROJECT_MAGNIFICATION = "Instrument Project Magnification"
PROP_INSTRUMENT_PROJECT_MAGNIFICATION_ALLOWED_VALUES = (
    "Instrument Project Magnification Allowed Values"
)
PROP_INSTRUMENT_PROJECT_CAMERA_LENGTH_CENTIMETERS = (
    "Instrument Project Camera Length (centimeters)"
)
PROP_INSTRUMENT_PROJECT_CAMERA_LENGTH_ALLOWED_VALUES = (
    "Instrument Project Camera Length Allowed Values"
)
PROP_INSTRUMENT_PROJECT_NAME = "Instrument Project Name"
PROP_INSTRUMENT_PROJECT_MODE = "Instrument Project Mode"
PROP_INSTRUMENT_PROJECT_SUB_MODE = "Instrument Project Sub Mode"
PROP_INSTRUMENT_PROJECT_TEMSTEMMODE = "Instrument Project TEMorSTEM Mode"
PROP_INSTRUMENT_ACCEL_VOLTAGE = "Instrument Accelerating Voltage (V)"
PROP_INSTRUMENT_ACCEL_VOLTAGE_ALLOWED_VALUES = (
    "Instrument Accelerating Voltage (V) Allowed Values"
)
PROP_INSTRUMENT_SCREEN_POSITION = "Instrument Screen Position"
PROP_INSTRUMENT_BEAM_BLANKING = "Instrument Beam Blanking"
PROP_INTERLOCK_TEMP_SENSOR_SOURCE = "Interlock Temp Sensor Source"
PROP_INTERLOCK_PRESSURE_SENSOR_SOURCE = "Interlock Pressure Sensor Source"
PROP_MSC_I2C_TYPE = "MSC I2C Bus Type"
PROP_INTERRUPT_STATUS = "Interrupt Status"
PROP_LEVEL_0_MERGE_MAXIMUM_BIN1X = "Level 0 Merge Maximum Bin1x"
PROP_LEVEL_0_MERGE_MAXIMUM_BIN2X = "Level 0 Merge Maximum Bin2x"
PROP_LEVEL_0_MERGE_MINIMUM_BIN1X = "Level 0 Merge Minimum Bin1x"
PROP_LEVEL_0_MERGE_MINIMUM_BIN2X = "Level 0 Merge Minimum Bin2x"
PROP_LEVEL_0_THRESHOLD_BIN1X_RS = "Level 0 Threshold Bin1x RS"
PROP_LEVEL_0_THRESHOLD_BIN2X_RS = "Level 0 Threshold Bin2x RS"
PROP_LEVEL_0_THRESHOLD_BIN1X_GS = "Level 0 Threshold Bin1x GS"
PROP_LEVEL_0_THRESHOLD_BIN2X_GS = "Level 0 Threshold Bin2x GS"
PROP_LEVEL_1_GAIN_FACTOR_BIN1X = "Level 1 Gain Factor Bin1x"
PROP_LEVEL_1_GAIN_FACTOR_BIN2X = "Level 1 Gain Factor Bin2x"
PROP_LEVEL_1_MERGE_MAXIMUM_BIN1X = "Level 1 Merge Maximum Bin1x"
PROP_LEVEL_1_MERGE_MAXIMUM_BIN2X = "Level 1 Merge Maximum Bin2x"
PROP_LEVEL_1_MERGE_MINIMUM_BIN1X = "Level 1 Merge Minimum Bin1x"
PROP_LEVEL_1_MERGE_MINIMUM_BIN2X = "Level 1 Merge Minimum Bin2x"
PROP_LEVEL_1_THRESHOLD_BIN1X_RS = "Level 1 Threshold Bin1x RS"
PROP_LEVEL_1_THRESHOLD_BIN2X_RS = "Level 1 Threshold Bin2x RS"
PROP_LEVEL_1_THRESHOLD_BIN1X_GS = "Level 1 Threshold Bin1x GS"
PROP_LEVEL_1_THRESHOLD_BIN2X_GS = "Level 1 Threshold Bin2x GS"
PROP_LEVEL_2_GAIN_FACTOR_BIN1X = "Level 2 Gain Factor Bin1x"
PROP_LEVEL_2_GAIN_FACTOR_BIN2X = "Level 2 Gain Factor Bin2x"
PROP_LEVEL_2_THRESHOLD_BIN1X_RS = "Level 2 Threshold Bin1x RS"
PROP_LEVEL_2_THRESHOLD_BIN2X_RS = "Level 2 Threshold Bin2x RS"
PROP_LEVEL_2_THRESHOLD_BIN1X_GS = "Level 2 Threshold Bin1x GS"
PROP_LEVEL_2_THRESHOLD_BIN2X_GS = "Level 2 Threshold Bin2x GS"
PROP_LICENSE_4D_STEM_WORKFLOW = "License - 4D STEM Workflow"
PROP_LICENSE_EVENT_COUNTING = "License - Event Counting"
PROP_LICENSE_HDR_READOUT_MODES = "License - HDR Readout Modes"
PROP_LOCAL_TIME = "Local time"
PROP_LOG_LEVEL = "Log Level"
PROP_MEASURED_FRAME_RATE = "Measured Frame Rate"
PROP_NUMBER_OF_FRAMES_GRABBED = "Number of Frames Grabbed"
PROP_NUMBER_OF_FRAMES_PROCESSED = "Number of Frames Processed"
PROP_NUMBER_OF_FRAMES_REQUESTED = "Number of Frames Requested"
PROP_NUMBER_OF_FRAMES_TO_GRAB = "Number of Frames To Grab"
PROP_OUTPUT_SEMAPHORE_BYPASS = "Output Semaphore Bypass"
PROP_POST_SPECIMEN_SHUTTER_CONTROL = "Post-Specimen Shutter Control"
PROP_POST_SPECIMEN_SHUTTER_INVERT = "Post-Specimen Shutter Invert"
PROP_PRE_EXPOSURE_TIME_SECONDS = "Pre-Exposure Time (seconds)"
PROP_PRE_SPECIMEN_BLANKER_CONTROL = "Pre-Specimen Blanker Control"
PROP_PRE_SPECIMEN_BLANKER_INVERT = "Pre-Specimen Blanker Invert"
PROP_PRESET_CURRENT = "Preset - Current"
PROP_PRESET_LIST = "Preset - List"
PROP_PRESET_PROPERTIES = "Preset - Properties"
PROP_PRESET_SAVE = "Preset - Save"
PROP_PROPERTY_CHANGE_DURING_ACQUISITION = "Property Change During Acquisition"
PROP_PROTECTION_COVER_DELAY_MILLISECONDS = "Protection Cover Delay (milliseconds)"
PROP_PROTECTION_COVER_OPERATION_MODE = "Protection Cover Operation Mode"
PROP_PROTECTION_COVER_STATUS = "Protection Cover Status"
PROP_READOUT_FRAMES_TO_IGNORE = "Readout - Frames to Ignore"
PROP_READOUT_HARDWARE_HDR = "Readout - Hardware HDR"
PROP_READOUT_SHUTTER = "Readout - Shutter"
PROP_REFERENCE_COUNTING_GAIN = "Reference - Counting Gain"
PROP_REFERENCE_COUNTING_GAIN_ACQUISITIONS = "Reference - Counting Gain Acquisitions"
PROP_REFERENCE_COUNTING_GAIN_EXPOSURE_TIME_SECONDS = (
    "Reference - Counting Gain Exposure Time (seconds)"
)
PROP_REFERENCE_COUNTING_GAIN_TARGET = "Reference - Counting Gain Target (e-/pix)"
PROP_REFERENCE_DARK = "Reference - Dark"
PROP_REFERENCE_DELAY_BETWEEN_MULTIPLE_ACQUISITIONS_MILLISECONDS = (
    "Reference - Delay Between Multiple Acquisitions (milliseconds)"
)
PROP_REFERENCE_EXPOSURE_LEVEL = "Reference - Exposure Level"
PROP_REFERENCE_GAIN = "Reference - Gain"
PROP_REFERENCE_INTEGRATING_GAIN = "Reference - Integrating Gain"
PROP_REFERENCE_HDR_GAIN = "Reference - HDR Gain"
PROP_REFERENCE_HIGH_GAIN = "Reference - High Gain"
PROP_REFERENCE_INTEGRATING_GAIN_ACQUISITIONS = (
    "Reference - Integrating Gain Acquisitions"
)
PROP_REFERENCE_INTEGRATING_GAIN_EXPOSURE_TIME_SECONDS = (
    "Reference - Integrating Gain Exposure Time (seconds)"
)
PROP_REFERENCE_INTEGRATING_GAIN_TARGET = "Reference - Integrating Gain Target (ADU/pix)"
PROP_REFERENCE_GAIN_ACQUISITIONS_IN_ENGINEERING_MODE = (
    "Reference - Number of Gain Acquisitions in Engineering Mode"
)
PROP_REFERENCE_LOW_GAIN = "Reference - Low Gain"
PROP_REFERENCE_MATCH_FRAME_RATE = "Reference - Match Frame Rate"
PROP_REFERENCE_MATCH_ROI = "Reference - Match ROI"
PROP_REFERENCE_MATCH_SERVER_VERSION = "Reference - Match Server Version"
PROP_REFERENCE_NUMBERS_TO_KEEP = "Reference - Numbers To Keep"
PROP_REFERENCE_SAVE_SINGLE_REFERENCES = "Reference - Save Single References"
PROP_REFERENCE_SAVE_COPY = "Reference - Save Copy"
PROP_REMAINING_NUMBER_OF_ACQUISITIONS = "Remaining Number of Acquisitions"
PROP_SCAN_ASSERT_SCAN_CONTROL_WHEN_NOT_SCANNING = (
    "Scan - Assert Scan Control When Not Scanning"
)
PROP_SCAN_BLANK_BEAM_WHEN_NOT_SCANNING = "Scan - Blank Beam When Not Scanning"
PROP_SCAN_BLANKER_INVERT = "Scan - Blanker Invert"
PROP_SCAN_CAMERA_FRAMES_PER_POINT = "Scan - Camera Frames Per Point"
PROP_SCAN_CONTROLLER = "Scan - Controller"
PROP_SCAN_DISTORTION_CORRECTION_ENABLE = "Scan - Distortion Correction Enable"
PROP_SCAN_DISTORTION_CORRECTION_PARAMETER1 = "Scan - Distortion Correction Parameter 1"
PROP_SCAN_DISTORTION_CORRECTION_PARAMETER2 = "Scan - Distortion Correction Parameter 2"
PROP_SCAN_DWELL_TIME_MICROSECONDS = "Scan - Dwell Time (microseconds)"
PROP_SCAN_ENABLE = "Scan - Enable"
PROP_SCAN_EXTERNAL_DETECTOR_1_AUTOADJUST = "Scan - External Detector 1 Auto Adjust"
PROP_SCAN_EXTERNAL_DETECTOR_1_ENABLE = "Scan - External Detector 1 Enable"
PROP_SCAN_EXTERNAL_DETECTOR_1_GAIN = "Scan - External Detector 1 Gain"
PROP_SCAN_EXTERNAL_DETECTOR_1_NAME = "Scan - External Detector 1 Name"
PROP_SCAN_EXTERNAL_DETECTOR_1_OFFSET = "Scan - External Detector 1 Offset"
PROP_SCAN_EXTERNAL_DETECTOR_2_AUTOADJUST = "Scan - External Detector 2 Auto Adjust"
PROP_SCAN_EXTERNAL_DETECTOR_2_ENABLE = "Scan - External Detector 2 Enable"
PROP_SCAN_EXTERNAL_DETECTOR_2_GAIN = "Scan - External Detector 2 Gain"
PROP_SCAN_EXTERNAL_DETECTOR_2_NAME = "Scan - External Detector 2 Name"
PROP_SCAN_EXTERNAL_DETECTOR_2_OFFSET = "Scan - External Detector 2 Offset"
PROP_SCAN_EXTERNAL_DETECTOR_3_AUTOADJUST = "Scan - External Detector 3 Auto Adjust"
PROP_SCAN_EXTERNAL_DETECTOR_3_ENABLE = "Scan - External Detector 3 Enable"
PROP_SCAN_EXTERNAL_DETECTOR_3_GAIN = "Scan - External Detector 3 Gain"
PROP_SCAN_EXTERNAL_DETECTOR_3_NAME = "Scan - External Detector 3 Name"
PROP_SCAN_EXTERNAL_DETECTOR_3_OFFSET = "Scan - External Detector 3 Offset"
PROP_SCAN_EXTERNAL_DETECTOR_4_AUTOADJUST = "Scan - External Detector 4 Auto Adjust"
PROP_SCAN_EXTERNAL_DETECTOR_4_ENABLE = "Scan - External Detector 4 Enable"
PROP_SCAN_EXTERNAL_DETECTOR_4_GAIN = "Scan - External Detector 4 Gain"
PROP_SCAN_EXTERNAL_DETECTOR_4_NAME = "Scan - External Detector 4 Name"
PROP_SCAN_EXTERNAL_DETECTOR_4_OFFSET = "Scan - External Detector 4 Offset"
PROP_SCAN_FLIP_HORIZONTALLY = "Scan - Flip Horizontally"
PROP_SCAN_FLIP_VERTICALLY = "Scan - Flip Vertically"
PROP_SCAN_INITIAL_DELAY_MICROSECONDS = "Scan - Initial Delay (microseconds)"
PROP_SCAN_FLYBACK_TIME_POSITIVE_MICROSECONDS = (
    "Scan - Flyback Time Going Positive (microseconds)"
)
PROP_SCAN_FLYBACK_TIME_NEGATIVE_MICROSECONDS = (
    "Scan - Flyback Time Going Negative (microseconds)"
)
PROP_SCAN_FREESCAN_GEN = "Scan - FreeScan Gen"
PROP_SCAN_IO_DEVICE_MODEL = "Scan - IO Device Model"
PROP_SCAN_IO_DEVICE_NAME = "Scan - IO Device Name"
PROP_SCAN_POINTS = "Scan - Points"
PROP_SCAN_POINTS_PER_CAMERA_FRAME = "Scan - Points Per Camera Frame"
PROP_SCAN_PRESET_CURRENT = "Scan - Preset Current"
PROP_SCAN_PRESET_LIST = "Scan - Preset List"
PROP_SCAN_PRESET_SAVE = "Scan - Preset Save"
PROP_SCAN_ROI_ENABLE = "Scan - ROI Enable"
PROP_SCAN_ROI_OFFSET_X = "Scan - ROI Offset X"
PROP_SCAN_ROI_OFFSET_Y = "Scan - ROI Offset Y"
PROP_SCAN_ROI_SIZE_X = "Scan - ROI Size X"
PROP_SCAN_ROI_SIZE_Y = "Scan - ROI Size Y"
PROP_SCAN_ROI_SUBSAMPLING = "Scan - ROI Subsampling"
PROP_SCAN_ROI_SUBSAMPLING_IS_RANDOM = "Scan - ROI Subsampling Is Random"
PROP_SCAN_ROI_UPSAMPLING = "Scan - ROI Upsampling"
PROP_SCAN_ROI_TYPE = "Scan - ROI Type"
PROP_SCAN_LINK_ROI_TYPE_TO_TYPE = "Scan - Link ROI Type to Type"
PROP_SCAN_PARK_ENABLE = "Scan - Park Enable"
PROP_SCAN_PARK_POSITION_X = "Scan - Park Position X"
PROP_SCAN_PARK_POSITION_Y = "Scan - Park Position Y"
PROP_SCAN_REPEAT_DELAY_SECONDS = "Scan - Repeat Delay (seconds)"
PROP_SCAN_REPEATS = "Scan - Repeats"
PROP_SCAN_ROTATION = "Scan - Rotation"
PROP_SCAN_SIZE_X = "Scan - Size X"
PROP_SCAN_SIZE_Y = "Scan - Size Y"
PROP_SCAN_SUBSAMPLING = "Scan - Subsampling"
PROP_SCAN_SUBSAMPLING_IS_RANDOM = "Scan - Subsampling Is Random"
PROP_SCAN_TIME_PER_SCAN_SECONDS = "Scan - Time Per Scan (seconds)"
PROP_SCAN_TIME_TOTAL_SECONDS = "Scan - Time (seconds)"
PROP_SCAN_TRIGGER_SOURCE = "Scan - Trigger Source"
PROP_SCAN_TYPE = "Scan - Type"
PROP_SCAN_USE_DE_CAMERA = "Scan - Use DE Camera"
PROP_SCAN_VIRTUAL_DETECTOR_0_CALCULATION = "Scan - Virtual Detector 0 Calculation"
PROP_SCAN_VIRTUAL_DETECTOR_0_NAME = "Scan - Virtual Detector 0 Name"
PROP_SCAN_VIRTUAL_DETECTOR_0_PLUS_HEIGHT = "Scan - Virtual Detector 0 Plus Height"
PROP_SCAN_VIRTUAL_DETECTOR_0_PLUS_LEFT = "Scan - Virtual Detector 0 Plus Left"
PROP_SCAN_VIRTUAL_DETECTOR_0_PLUS_TOP = "Scan - Virtual Detector 0 Plus Top"
PROP_SCAN_VIRTUAL_DETECTOR_0_PLUS_WIDTH = "Scan - Virtual Detector 0 Plus Width"
PROP_SCAN_VIRTUAL_DETECTOR_0_SHAPE = "Scan - Virtual Detector 0 Shape"
PROP_SCAN_VIRTUAL_DETECTOR_1_CALCULATION = "Scan - Virtual Detector 1 Calculation"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_ANGLE_IN = "Scan - Virtual Detector 1 Minus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_ANGLE_OUT = (
    "Scan - Virtual Detector 1 Minus Angle Out"
)
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_CENTER_X = "Scan - Virtual Detector 1 Minus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_CENTER_Y = "Scan - Virtual Detector 1 Minus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_HEIGHT = "Scan - Virtual Detector 1 Minus Height"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_LEFT = "Scan - Virtual Detector 1 Minus Left"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_RADIUS_X = "Scan - Virtual Detector 1 Minus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_RADIUS_Y = "Scan - Virtual Detector 1 Minus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_THICKNESS = (
    "Scan - Virtual Detector 1 Minus Thickness"
)
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_TOP = "Scan - Virtual Detector 1 Minus Top"
PROP_SCAN_VIRTUAL_DETECTOR_1_MINUS_WIDTH = "Scan - Virtual Detector 1 Minus Width"
PROP_SCAN_VIRTUAL_DETECTOR_1_NAME = "Scan - Virtual Detector 1 Name"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_ANGLE_IN = "Scan - Virtual Detector 1 Plus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_ANGLE_OUT = "Scan - Virtual Detector 1 Plus Angle Out"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_CENTER_X = "Scan - Virtual Detector 1 Plus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_CENTER_Y = "Scan - Virtual Detector 1 Plus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_HEIGHT = "Scan - Virtual Detector 1 Plus Height"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_LEFT = "Scan - Virtual Detector 1 Plus Left"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_RADIUS_X = "Scan - Virtual Detector 1 Plus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_RADIUS_Y = "Scan - Virtual Detector 1 Plus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_THICKNESS = "Scan - Virtual Detector 1 Plus Thickness"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_TOP = "Scan - Virtual Detector 1 Plus Top"
PROP_SCAN_VIRTUAL_DETECTOR_1_PLUS_WIDTH = "Scan - Virtual Detector 1 Plus Width"
PROP_SCAN_VIRTUAL_DETECTOR_1_PRESET_CURRENT = "Scan - Virtual Detector 1 Preset Current"
PROP_SCAN_VIRTUAL_DETECTOR_1_PRESET_SAVE = "Scan - Virtual Detector 1 Preset Save"
PROP_SCAN_VIRTUAL_DETECTOR_1_SHAPE = "Scan - Virtual Detector 1 Shape"
PROP_SCAN_VIRTUAL_DETECTOR_2_CALCULATION = "Scan - Virtual Detector 2 Calculation"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_ANGLE_IN = "Scan - Virtual Detector 2 Minus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_ANGLE_OUT = (
    "Scan - Virtual Detector 2 Minus Angle Out"
)
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_CENTER_X = "Scan - Virtual Detector 2 Minus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_CENTER_Y = "Scan - Virtual Detector 2 Minus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_HEIGHT = "Scan - Virtual Detector 2 Minus Height"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_LEFT = "Scan - Virtual Detector 2 Minus Left"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_RADIUS_X = "Scan - Virtual Detector 2 Minus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_RADIUS_Y = "Scan - Virtual Detector 2 Minus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_THICKNESS = (
    "Scan - Virtual Detector 2 Minus Thickness"
)
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_TOP = "Scan - Virtual Detector 2 Minus Top"
PROP_SCAN_VIRTUAL_DETECTOR_2_MINUS_WIDTH = "Scan - Virtual Detector 2 Minus Width"
PROP_SCAN_VIRTUAL_DETECTOR_2_NAME = "Scan - Virtual Detector 2 Name"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_ANGLE_IN = "Scan - Virtual Detector 2 Plus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_ANGLE_OUT = "Scan - Virtual Detector 2 Plus Angle Out"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_CENTER_X = "Scan - Virtual Detector 2 Plus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_CENTER_Y = "Scan - Virtual Detector 2 Plus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_HEIGHT = "Scan - Virtual Detector 2 Plus Height"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_LEFT = "Scan - Virtual Detector 2 Plus Left"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_RADIUS_X = "Scan - Virtual Detector 2 Plus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_RADIUS_Y = "Scan - Virtual Detector 2 Plus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_THICKNESS = "Scan - Virtual Detector 2 Plus Thickness"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_TOP = "Scan - Virtual Detector 2 Plus Top"
PROP_SCAN_VIRTUAL_DETECTOR_2_PLUS_WIDTH = "Scan - Virtual Detector 2 Plus Width"
PROP_SCAN_VIRTUAL_DETECTOR_2_PRESET_CURRENT = "Scan - Virtual Detector 2 Preset Current"
PROP_SCAN_VIRTUAL_DETECTOR_2_PRESET_SAVE = "Scan - Virtual Detector 2 Preset Save"
PROP_SCAN_VIRTUAL_DETECTOR_2_SHAPE = "Scan - Virtual Detector 2 Shape"
PROP_SCAN_VIRTUAL_DETECTOR_3_CALCULATION = "Scan - Virtual Detector 3 Calculation"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_ANGLE_IN = "Scan - Virtual Detector 3 Minus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_ANGLE_OUT = (
    "Scan - Virtual Detector 3 Minus Angle Out"
)
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_CENTER_X = "Scan - Virtual Detector 3 Minus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_CENTER_Y = "Scan - Virtual Detector 3 Minus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_HEIGHT = "Scan - Virtual Detector 3 Minus Height"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_LEFT = "Scan - Virtual Detector 3 Minus Left"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_RADIUS_X = "Scan - Virtual Detector 3 Minus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_RADIUS_Y = "Scan - Virtual Detector 3 Minus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_THICKNESS = (
    "Scan - Virtual Detector 3 Minus Thickness"
)
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_TOP = "Scan - Virtual Detector 3 Minus Top"
PROP_SCAN_VIRTUAL_DETECTOR_3_MINUS_WIDTH = "Scan - Virtual Detector 3 Minus Width"
PROP_SCAN_VIRTUAL_DETECTOR_3_NAME = "Scan - Virtual Detector 3 Name"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_ANGLE_IN = "Scan - Virtual Detector 3 Plus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_ANGLE_OUT = "Scan - Virtual Detector 3 Plus Angle Out"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_CENTER_X = "Scan - Virtual Detector 3 Plus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_CENTER_Y = "Scan - Virtual Detector 3 Plus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_HEIGHT = "Scan - Virtual Detector 3 Plus Height"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_LEFT = "Scan - Virtual Detector 3 Plus Left"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_RADIUS_X = "Scan - Virtual Detector 3 Plus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_RADIUS_Y = "Scan - Virtual Detector 3 Plus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_THICKNESS = "Scan - Virtual Detector 3 Plus Thickness"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_TOP = "Scan - Virtual Detector 3 Plus Top"
PROP_SCAN_VIRTUAL_DETECTOR_3_PLUS_WIDTH = "Scan - Virtual Detector 3 Plus Width"
PROP_SCAN_VIRTUAL_DETECTOR_3_PRESET_CURRENT = "Scan - Virtual Detector 3 Preset Current"
PROP_SCAN_VIRTUAL_DETECTOR_3_PRESET_SAVE = "Scan - Virtual Detector 3 Preset Save"
PROP_SCAN_VIRTUAL_DETECTOR_3_SHAPE = "Scan - Virtual Detector 3 Shape"
PROP_SCAN_VIRTUAL_DETECTOR_4_CALCULATION = "Scan - Virtual Detector 4 Calculation"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_ANGLE_IN = "Scan - Virtual Detector 4 Minus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_ANGLE_OUT = (
    "Scan - Virtual Detector 4 Minus Angle Out"
)
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_CENTER_X = "Scan - Virtual Detector 4 Minus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_CENTER_Y = "Scan - Virtual Detector 4 Minus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_HEIGHT = "Scan - Virtual Detector 4 Minus Height"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_LEFT = "Scan - Virtual Detector 4 Minus Left"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_RADIUS_X = "Scan - Virtual Detector 4 Minus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_RADIUS_Y = "Scan - Virtual Detector 4 Minus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_THICKNESS = (
    "Scan - Virtual Detector 4 Minus Thickness"
)
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_TOP = "Scan - Virtual Detector 4 Minus Top"
PROP_SCAN_VIRTUAL_DETECTOR_4_MINUS_WIDTH = "Scan - Virtual Detector 4 Minus Width"
PROP_SCAN_VIRTUAL_DETECTOR_4_NAME = "Scan - Virtual Detector 4 Name"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_ANGLE_IN = "Scan - Virtual Detector 4 Plus Angle In"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_ANGLE_OUT = "Scan - Virtual Detector 4 Plus Angle Out"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_CENTER_X = "Scan - Virtual Detector 4 Plus Center X"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_CENTER_Y = "Scan - Virtual Detector 4 Plus Center Y"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_HEIGHT = "Scan - Virtual Detector 4 Plus Height"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_LEFT = "Scan - Virtual Detector 4 Plus Left"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_RADIUS_X = "Scan - Virtual Detector 4 Plus Radius X"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_RADIUS_Y = "Scan - Virtual Detector 4 Plus Radius Y"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_THICKNESS = "Scan - Virtual Detector 4 Plus Thickness"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_TOP = "Scan - Virtual Detector 4 Plus Top"
PROP_SCAN_VIRTUAL_DETECTOR_4_PLUS_WIDTH = "Scan - Virtual Detector 4 Plus Width"
PROP_SCAN_VIRTUAL_DETECTOR_4_PRESET_CURRENT = "Scan - Virtual Detector 4 Preset Current"
PROP_SCAN_VIRTUAL_DETECTOR_4_PRESET_SAVE = "Scan - Virtual Detector 4 Preset Save"
PROP_SCAN_VIRTUAL_DETECTOR_4_SHAPE = "Scan - Virtual Detector 4 Shape"
PROP_SCAN_VIRTUAL_DETECTOR_PRESET_LIST = "Scan - Virtual Detector Preset List"
PROP_SCAN_VOLTAGE_H_MAX = "Scan - Voltage H Max"
PROP_SCAN_VOLTAGE_H_MIN = "Scan - Voltage H Min"
PROP_SCAN_VOLTAGE_V_MAX = "Scan - Voltage V Max"
PROP_SCAN_VOLTAGE_V_MIN = "Scan - Voltage V Min"
PROP_SCAN_WAIT_SECONDS = "Scan - Wait (seconds)"
PROP_SCAN_XY_FILE = "Scan - XY File"
PROP_SCAN_XY_FILE_PATTERN_ID = "Scan - XY File Pattern ID"
PROP_SENSOR_CLOCK_FREQUENCY = "Sensor Clock Frequency"
PROP_SENSOR_COARSE_GAIN = "Sensor Coarse Gain"
PROP_SENSOR_CONSISTENT_READOUT = "Sensor Consistent Readout"
PROP_SENSOR_CONTINUOUS_READOUT = "Sensor Continuous Readout"
PROP_SENSOR_M1_CLEARING_SETTING = "Sensor M1 Clearing Setting"
PROP_SENSOR_MODULE_SN = "Sensor Module SN"
PROP_SENSOR_N_TUNER_COLUMN_SETTING = "Sensor N Tuner Column Setting"
PROP_SENSOR_PIXEL_DEPTH = "Sensor Pixel Depth"
PROP_SENSOR_PIXEL_PITCH_MICROMETERS = "Sensor Pixel Pitch (micrometers)"
PROP_SENSOR_READOUT_DELAY_MILLISECONDS = "Sensor Readout Delay (milliseconds)"
PROP_SENSOR_RESET = "Sensor Reset"
PROP_SENSOR_SEQUENCE_SELECT = "Sensor Sequence Select"
PROP_SENSOR_SIZE_X_PIXELS = "Sensor Size X (pixels)"
PROP_SENSOR_SIZE_Y_PIXELS = "Sensor Size Y (pixels)"
PROP_SENSOR_TG_PULSE_LENGTH = "Sensor TG Pulse Length"
PROP_SENSOR_THRESHOLD = "Sensor Threshold"
PROP_SERVER_IP_ADDRESSS = "Server IP Addresss"
PROP_SERVER_PORT_NUMBER = "Server Port Number"
PROP_SERVER_PROCESS_ID = "Server Process ID"
PROP_SERVER_SOFTWARE_VERSION = "Server Software Version"
PROP_SPECIMEN_PIXEL_SIZE_X_NANOMETERS = "Specimen Pixel Size X (nanometers)"
PROP_SPECIMEN_PIXEL_SIZE_Y_NANOMETERS = "Specimen Pixel Size Y (nanometers)"
PROP_DIFFRACTION_PIXEL_SIZE_X = "Diffraction Pixel Size X"
PROP_DIFFRACTION_PIXEL_SIZE_Y = "Diffraction Pixel Size Y"
PROP_SPEED_FRAME_INPUT_WAIT_US = "Speed - Frame Input Wait (us)"
PROP_SPEED_FRAME_INPUT_TIME_US = "Speed - Frame Input Time (us)"
PROP_SPEED_FRAME_WRITE_TIME_US = "Speed - Frame Write Time (us)"
PROP_SPEED_FRAME_OUTPUT_WAIT_US = "Speed - Frame output Wait (us)"
PROP_SPEED_FRAME_OUTPUT_TIME_US = "Speed - Frame output Time (us)"
PROP_SPEED_GRABBING = "Speed - Grabbing (MB/s)"
PROP_SPEED_PROCESSING = "Speed - Processing (MB/s)"
PROP_SYSTEM_STATUS = "System Status"
PROP_SYSTEM_TEMPERATURE_ADC = "System Temperature - ADC (0.1 K)"
PROP_SYSTEM_TEMPERATURE_ADC_0 = "System Temperature - ADC 0 (0.1 K)"
PROP_SYSTEM_TEMPERATURE_ADC_1 = "System Temperature - ADC 1 (0.1 K)"
PROP_SYSTEM_TEMPERATURE_ADC_2 = "System Temperature - ADC 2 (0.1 K)"
PROP_SYSTEM_TEMPERATURE_CXP_LOWER_FPGA = "System Temperature - CXP Lower FPGA (0.1 K)"
PROP_SYSTEM_TEMPERATURE_CXP_UPPER_FPGA = "System Temperature - CXP Upper FPGA (0.1 K)"
PROP_SYSTEM_TEMPERATURE_HEAT_EXCHANGER = "System Temperature - Heat Exchanger (0.1 K)"
PROP_SYSTEM_TEMPERATURE_TEC_MOSFET_A = "System Temperature - TEC MOSFET A (0.1 K)"
PROP_SYSTEM_TEMPERATURE_TEC_MOSFET_B = "System Temperature - TEC MOSFET B (0.1 K)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_1_8_V = "System Voltage - Main Sensor 1.8 V (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_3_3_VA = "System Voltage - Main Sensor 3.3 VA (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_3_3_VD = "System Voltage - Main Sensor 3.3 VD (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_4_6_V = "System Voltage - Main Sensor 4.6 V (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_DC2 = "System Voltage - Main Sensor DC2 (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_DC2_SETPOINT = (
    "System Voltage - Main Sensor DC2 Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_SPARE3 = "System Voltage - Main Sensor SPARE3 (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_SPARE3_SETPOINT = (
    "System Voltage - Main Sensor SPARE3 Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VCM = "System Voltage - Main Sensor VCM (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VCM_SETPOINT = (
    "System Voltage - Main Sensor VCM Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_PIX = "System Voltage - Main Sensor VDD Pix (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_PIX_SETPOINT = (
    "System Voltage - Main Sensor VDD Pix Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_RESET = (
    "System Voltage - Main Sensor VDD Reset (mV)"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_RESET_SETPOINT = (
    "System Voltage - Main Sensor VDD Reset Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_SERIE = (
    "System Voltage - Main Sensor VDD Serie (mV)"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_SERIE_SETPOINT = (
    "System Voltage - Main Sensor VDD Serie Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_TRANS = (
    "System Voltage - Main Sensor VDD Trans (mV)"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VDD_TRANS_SETPOINT = (
    "System Voltage - Main Sensor VDD Trans Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_COL = "System Voltage - Main Sensor VREF COL (mV)"
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_COL_SETPOINT = (
    "System Voltage - Main Sensor VREF COL Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_DIFF = (
    "System Voltage - Main Sensor VREF DIFF (mV)"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_DIFF_SETPOINT = (
    "System Voltage - Main Sensor VREF DIFF Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_GS_COL_SETPOINT = (
    "System Voltage - Main Sensor VREF GS COL Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_GS_DIFF_SETPOINT = (
    "System Voltage - Main Sensor VREF GS DIFF Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_RS_COL_SETPOINT = (
    "System Voltage - Main Sensor VREF RS COL Setpoint"
)
PROP_SYSTEM_VOLTAGE_MAIN_SENSOR_VREF_RS_DIFF_SETPOINT = (
    "System Voltage - Main Sensor VREF RS DIFF Setpoint"
)
PROP_SYSTEM_VOLTAGE_OVERRIDE_SETPOINTS = "System Voltage - Override Setpoints"
PROP_SYSTEM_VOLTAGE_SUPPLY_06_V = "System Voltage - Supply 06 V (mV)"
PROP_SYSTEM_VOLTAGE_SUPPLY_18_V = "System Voltage - Supply 18 V (mV)"
PROP_SYSTEM_VOLTAGE_SUPPLY_30_V = "System Voltage - Supply 30 V (mV)"
PROP_SYSTEM_VOLTAGE_TEC_MOSFET_A = "System Voltage - TEC MOSFET A (mV)"
PROP_SYSTEM_VOLTAGE_TEC_MOSFET_B = "System Voltage - TEC MOSFET B (mV)"
PROP_SYSTEM_VOLTAGE_VACUUM_04_1_V = "System Voltage - Vacuum 04.1 V (mV)"
PROP_SYSTEM_VOLTAGE_VACUUM_05_0_V = "System Voltage - Vacuum 05.0 V (mV)"
PROP_SYSTEM_VOLTAGE_VACUUM_30_0_V = "System Voltage - Vacuum 30.0 V (mV)"
PROP_TEMPERATURE_CHILLED_WATER = "Temperature - Chilled Water (Celsius)"
PROP_TEMPERATURE_CHILLED_WATER_STATUS = "Temperature - Chilled Water Status"
PROP_TEMPERATURE_CHILLED_WATER_THRESHOLD = (
    "Temperature - Chilled Water Threshold (Celsius)"
)
PROP_TEMPERATURE_COLD_FINGER = "Temperature - Cold Finger (Celsius)"
PROP_TEMPERATURE_CONTROL = "Temperature - Control"
PROP_TEMPERATURE_CONTROL_MODE = "Temperature - Control Mode"
PROP_TEMPERATURE_COOL_DOWN_SETPOINT = "Temperature - Cool Down Setpoint (Celsius)"
PROP_TEMPERATURE_DETECTOR = "Temperature - Detector (Celsius)"
PROP_TEMPERATURE_DETECTOR_STATUS = "Temperature - Detector Status"
PROP_TEMPERATURE_FLUCTUATION_TOLERANCE = "Temperature - Fluctuation Tolerance (Celsius)"
PROP_TEMPERATURE_MONITOR_PERIOD_SECOND = "Temperature - Monitor Period (second)"
PROP_TEMPERATURE_TEC_CURRENT = "Temperature - TEC Current (Ampere)"
PROP_TEMPERATURE_VALUE_TOLERANCE = "Temperature - Value Tolerance (Celsius)"
PROP_TEMPERATURE_WARM_UP_SETPOINT = "Temperature - Warm Up Setpoint (Celsius)"
PROP_TEST_PATTERN = "Test Pattern"
PROP_THRESHOLD_ADAPTIVE_THRESHOLDING_METHOD = "Threshold - Adaptive Thresholding Method"
PROP_THRESHOLD_METHOD = "Threshold - Method"
PROP_TIMESTAMP_SECONDS_SINCE_EPOCH = "Timestamp (seconds since Epoch)"
PROP_TOTAL_NUMBER_OF_ACQUISITIONS = "Total Number of Acquisitions"
PROP_VACUUM_STATE = "Vacuum State"
PROP_VIRTUAL_IMAGE_PIXEL_FORMAT = "Virtual Image Pixel Format"
PROP_CENTROIDING_MODE = "Centroiding Mode"
PROP_CENTROIDING_CLEAR_BUFFERS = "Centroiding Clear Buffers"
PROP_VOLTAGE_POWER_P_12_V = "Voltage - Power +12 (V)"
PROP_VOLTAGE_POWER_N_12_V = "Voltage - Power -12 (V)"
PROP_VOLTAGE_MOTOT_V = "Voltage - Motor (V)"
PROP_VOLTAGE_TEC_CONTROL_V = "Voltage - TEC control (V)"
PROP_BIAS_VOLTAGE_IMG = "Bias Voltage (IMG)"
PROP_BIAS_VOLTAGE_TREE = "Bias Voltage (TREE)"
PROP_BIAS_VOLTAGE_RST = "Bias Voltage (RST)"
PROP_BIAS_VOLTAGE_RST_LOW = "Bias Voltage (RST_LOW)"
PROP_PROTECTION_COVER_MANUAL_CONTROL = "Protection Cover Manual Control"
PROP_TEMPERATURE_SENSOR_USED_IN_CONTROL_LOOP = "Temperature Sensor Used in Control Loop"
PROP_TEMPERATURE_TEC_CTRL_MANUAL_MODE_DAC_COUNT = (
    "Temperature TEC Ctrl Manual Mode (DAC Count)"
)
PROP_OVERRIDE_FAILSAFE = "Override Failsafe"
PROP_SENSOR_CLOCK_RESET = "Sensor Clock Reset"
PROP_SENSOR_EXTERNAL_INTEGRATION_TIME_MILLISECONDS = (
    "Sensor External Integration Time (milliseconds)"
)
PROP_SENSOR_FRAME_TIME_MILLISECONDS = "Sensor Frame Time (milliseconds)"
PROP_SENSOR_FRAME_TIME_CALCULATED_MILLISECONDS = (
    "Sensor Frame Time Calculated (milliseconds)"
)
PROP_SHUTTER_PULSE_WIDTH_P_MILLISECONDS = "Shutter Pulse Width (+) (milliseconds)"
PROP_SHUTTER_PULSE_WIDTH_N_MILLISECONDS = "Shutter Pulse Width (-) (milliseconds)"
PROP_SHUTTER_PULSE_DELAY_IN_BETWEEN_MILLISECONDS = (
    "Shutter Pulse Delay in between (milliseconds)"
)
PROP_TEST_PATTERN_SEED = "Test Pattern Seed"
PROP_SENSOR_OFFSET_DACRAW = "Sensor Offset DACRAW"
PROP_SENSOR_OFFSET_DACFINE = "Sensor Offset DACFINE"
PROP_SESOR_CONTINUOUS_PRECHARGE = "Sensor Continuous Precharge"
PROP_OVERRIDE_FAILSAFE = "Override Failsafe"
PROP_SENSOR_EXTERNAL_INTEGRATION_TIME_MILLISECONDS = (
    "Sensor External Integration Time (milliseconds)"
)
PROP_SENSOR_FRAME_TIME_MILLISECONDS = "Sensor Frame Time (milliseconds)"
PROP_SENSOR_FRAME_TIME_CALCULATED_MILLISECONDS = (
    "Sensor Frame Time Calculated (milliseconds)"
)
PROP_PROTECTION_COVER_MANUAL_CONTROL = "Protection Cover Manual Control"
PROP_PROTECTION_COVER_OPEN_STEP_COUNT = "Protection Cover Open Step Count"
PROP_READOUT_OKRA = "Readout - OKRA"
PROP_READOUT_CDS = "Readout - CDS"
PROP_FARADAY_PLATE_BEAM_INTENSITY_PA_CM2 = "Faraday Plate - Beam Intensity (pA/cm^2)"
PROP_SENSOR_GAIN = "Sensor Gain"
PROP_SENSOR_FINE_GAIN = "Sensor Fine Gain"
PROP_SENSOR_OFFSET = "Sensor Offset"
PROP_READOUT_OKRA_SELECTION = "Readout - OKRA Selection"
PROP_ACQ_STATUS = "Acquisition Status"
PROP_ENGINEER_MODE = "Engineer Mode"
PROP_SIMULATOR_CONTRAST = "Simulator Contrast"
PROP_SIMULATOR_TARGET_CONTRAST_MIN = "Simulator Target Contrast Min"
PROP_SIMULATOR_TARGET_CONTRAST_MAX = "Simulator Target Contrast Max"
PROP_SIMULATOR_POISSON_NOISE = "Simulator Poisson Noise"
PROP_SIMULATOR_WALK = "Simulator Random Walk"
PROP_SIMULATOR_WALK_AMPLITUDE = "Simulator Random Walk Amplitude"
PROP_SIMULATOR_WALK_SD = "Simulator Random Walk Standard Deviation"
PROP_MOTION_CORRECTION = "Image Processing - Motion Correction"
PROP_MOTION_CORRECTION_EXTEND = (
    "Image Processing - Motion Correction Extend Pixel Values"
)
PROP_MOTION_CORRECTION_REFERENCE = (
    "Image Processing - Motion Correction Reference Image"
)
PROP_FINAL_IMAGE_INTENSITY_ADJUSTMENT = "Final Image Intensity Adjustment"
PROP_SERVER_NORMALIZE_PROPERTIES = "Server Normalize Properties"
